// <auto-generated />
using System;
using HrSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HrSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230130103838_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HrSystem.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("department_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            ManagerId = new Guid("bc528192-2726-4f85-b7f1-cc278a87052e"),
                            department_name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            ManagerId = new Guid("d36acd2e-1506-4362-9e16-6772008883b8"),
                            department_name = "Accounting"
                        });
                });

            modelBuilder.Entity("HrSystem.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("max_salary")
                        .HasColumnType("float");

                    b.Property<double>("min_salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02a73fcc-7bdf-4f47-99e5-3a00cbbd69d4"),
                            job_title = "Software Engineering",
                            max_salary = 5000.0,
                            min_salary = 1500.0
                        },
                        new
                        {
                            Id = new Guid("dbc5233f-d894-43cb-a3e3-e6b842a67feb"),
                            job_title = "Accountant",
                            max_salary = 4000.0,
                            min_salary = 1500.0
                        });
                });

            modelBuilder.Entity("HrSystem.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc528192-2726-4f85-b7f1-cc278a87052e"),
                            address = "Kofi Shito Street 45",
                            email = "rodgers@live.com",
                            manager_firstName = "Kenny",
                            manager_lastName = "Rodgers",
                            phone = "0243784512"
                        },
                        new
                        {
                            Id = new Guid("d36acd2e-1506-4362-9e16-6772008883b8"),
                            address = "Olusegu Obasanjo 12T",
                            email = "dolly@live.com",
                            manager_firstName = "Dolly",
                            manager_lastName = "Parton",
                            phone = "0206857945"
                        });
                });

            modelBuilder.Entity("HrSystem.Models.Department", b =>
                {
                    b.HasOne("HrSystem.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrSystem.Models.Manager", b =>
                {
                    b.HasOne("HrSystem.Models.Department", null)
                        .WithMany("Managers")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
